 apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - nodePort: 31321
      port: 81
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: myweb-deploy
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: myweb-image
      labels:
        app: webapp
    spec:
      containers:
      - name: myweb-image
        image: sulekha02112001/httpd-webserver:v2
        

