apiVersion: v1
kind: Service
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  ports:
    - port: 80
  selector:
    app: webpage
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: webpage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  selector:
    matchLabels:
      app: webpage
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webpage
        tier: frontend
    spec:
      containers:
      - image: sulekha02112001/kubectl:latest
        name: webpage
        ports:
        - containerPort: 80
          name: webpage
        volumeMounts:
        - name: webpage-persistent-volume 
          mountPath: /var/www/html
      volumes:
      - name: webpage-persistent-volume
        persistentVolumeClaim:
          claimName: wp-pv-claim

